name: monresto
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0-47.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

assets:
   - images/

fonts:
  - family: Montserrat
    fonts:
    - asset: assets/fonts/Montserrat-Regular.ttf
    - asset: assets/fonts/Montserrat-Bold.ttf
      weigth: 600
    - asset: assets/fonts/Montserrat-Black.ttf
      weigth: 800
    - asset: assets/fonts/Montserrat-Italic.ttf
      style: italic
    - asset: assets/fonts/Montserrat-Light.ttf
      weigth: 200
    - asset: assets/fonts/Montserrat-Medium.ttf
      weigth: 300
    - asset: assets/fonts/Montserrat-Thin.ttf
      weigth: 100
